name: Pulumi Preview
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to preview'
        required: true
env:
  DEV_ACCESS_KEY: ${{ secrets.DEV_ACCESS_KEY }}
  DEV_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET_ACCESS_KEY }}
  DEV_BUCKET_NAME: pulumi-state-backend-909397982620
  DEV_REGION: us-east-1

  TEST_ACCESS_KEY: ${{ secrets.TEST_ACCESS_KEY }}
  TEST_SECRET_ACCESS_KEY: ${{ secrets.TEST_SECRET_ACCESS_KEY }}
  TEST_BUCKET_NAME: pulumi-state-bucket-backend
  TEST_REGION: us-east-1

  STAGING_ACCESS_KEY: ${{ secrets.STAGING_ACCESS_KEY }}
  STAGING_SECRET_ACCESS_KEY: ${{ secrets.STAGING_SECRET_ACCESS_KEY }}
  STAGING_BUCKET_NAME: pulumi-state-backend-250550834778
  STAGING_REGION: us-east-1

  PRODUCTION_ACCESS_KEY: ${{ secrets.PRODUCTION_ACCESS_KEY }}
  PRODUCTION_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_SECRET_ACCESS_KEY }}
  PRODUCTION_BUCKET_NAME: pulumi-state-backend-297774485224    
  PRODUCTION_REGION: us-east-1        

jobs:
  pulumi-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$HOME/.pulumi/bin:$PATH
          pulumi version  

      - name: Install dependencies
        run: npm install  # or yarn install  

      - name: Configure AWS credentials
        run: |
          environment=${{ github.event.inputs.environment }}
          aws configure set aws_access_key_id ${{ env[environment + '_ACCESS_KEY'] }}
          aws configure set aws_secret_access_key ${{ env[environment + '_SECRET_ACCESS_KEY'] }}
          aws configure set region ${{ env[environment + '_REGION'] }}   

      - name: pulumi login s3
        run: |
            environment=${{ github.event.inputs.environment }}
            pulumi login s3://${{ env[environment + '_BUCKET_NAME'] }}
      
      - name: pulumi stacks
        run: |
           export PULUMI_CONFIG_PASSPHRASE=falkor
           pulumi stack ls 

      - name: Loop over stacks and perform preview
        env:
         PULUMI_CONFIG_PASSPHRASE: "falkor"
        run: |
           pulumi stack select dev-${{ github.event.inputs.environment }} || pulumi stack init dev-${{ github.event.inputs.environment }}
           pulumi preview

           pulumi stack select prod-${{ github.event.inputs.environment }} || pulumi stack init prod-${{ github.event.inputs.environment }}
           pulumi preview


