name: Pulumi Preview
on:
  pull_request:
    branches:
      - main

jobs:
  pulumi-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Install dependencies
        run: npm ci      

      - name: pulumi login s3
        run: |
           pulumi login s3://pulumi-ci-cd
      
      - name: pulumi stacks
        run: |
           export PULUMI_CONFIG_PASSPHRASE=falkor
           pulumi stack ls 

      - name: Loop over stacks and perform preview
        env:
         PULUMI_CONFIG_PASSPHRASE: "falkor"
        run: |
           pulumi stack ls --json | jq -r '.[].name' | grep -q "dev"
           dev_stack_exists=$?
           if [ $dev_stack_exists -ne 0 ]; then
           pulumi stack init dev
           fi

           pulumi stack ls --json | jq -r '.[].name' | grep -q "prod"
           prod_stack_exists=$?
           if [ $prod_stack_exists -ne 0 ]; then
           pulumi stack init prod
           fi

           pulumi stack select dev
           pulumi preview

           pulumi stack select prod
           pulumi preview

